### ISSUE TITLE
Cleanup python2

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#1870]
I cannot believe we didn't have an issue for this, it was on my radar to do when I needed a fun project (I like removing code).

This is a big cleanup effort, but it can be broken down to smaller pieces. Hardly any of the components need any experience with astroquery itself, thus the package-novice label, however, I don't expect this to be a low effort issue. The only ask is to be careful when using automated scripts (2to3) as many of the changes those tools suggest are unnecessary, etc. 
I believe we did some cleanups already, and using fstrings, etc, but many parts haven't been cleaned up.

The suggestion would be to comment here what aspect would you pick up on it, e.g. "removing six", etc.

- [x] cleanup future - #1864 
- [x] cleanup class definitions inherited from `object`  - #1872  #2392
- [x] cleanup six
- [x] cleanup try/excepts and if/elses done for python version
- [ ] cleanup any potential encoding related workarounds
- [x] cleanup any potential PEP 3151 (see https://github.com/astropy/astropy/pull/6932 for an example)  #2392
- [x] cleanup  most cases of `super()` as there is no need for classname and `self`  #2392
...

full example of python2 removal things from astropy: 
 - huge PR: https://github.com/astropy/astropy/pull/6556/files
 - list like the above:  https://github.com/astropy/astropy/issues/6234#issuecomment-328292343

**Comment by HarrietAkot** [comment]
Hello @bsipocz . I am an outreachy applicant. can I take up this issue?

**Comment by bsipocz** [comment]
Yes, absolutely. Please approach it modularly though as I would expect the whole python <3.6 cleanup would be quite substantial.

**Comment by HarrietAkot** [comment]
Thank you for your response. I will get to it as soon as possible

**Comment by bsipocz** [comment]
With  #2392 all the remaining, grep-able points here should be addressed.
