### ISSUE TITLE
Add `get_query_payload` consistently to all methods

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2040]
This is super valuable for debugging issues, e.g. I'm having troubles to catch the typo in a `Simbad.query_criteria()` call, and it doesn't have this kwarg.

Addressing the whole issue can be long, but the task is a package novice one, basically breakpoints needed to be added to return the payload strings rather than sending them to the server (and plenty of examples are available).

**Comment by jwoillez** [comment]
It is not exactly what you are looking for, but if you want to check the payloads as they are sent to the servers, you can use:

    from astroquery import log
    log.setLevel('DEBUG')

**Comment by bsipocz** [comment]
Yes, you're right, that works, too. But I would think it's still valuable to unify the API, as this is a bit more noisy than what I would need:

```
In [6]: Simbad.query_criteria("region(circle, ICRS, +00 01 57.9, -15 27 50, 1)", otype="Star", cache=False)
DEBUG: HTTP request
	-----------------------------------------
	POST http://simbad.u-strasbg.fr/simbad/sim-script
	User-Agent: astroquery/0.4.2.dev6653 python-requests/2.25.1
	Accept-Encoding: gzip, deflate
	Accept: */*
	Connection: keep-alive
	Cookie: JSESSIONID=70895933FD5399F3B323471C927B3ABE.new
	Content-Length: 173
	Content-Type: application/x-www-form-urlencoded

	script=%0Avotable+%7Bmain_id%2Ccoordinates%7D%0Avotable+open%0Aquery+sample++region%28circle%2C+ICRS%2C+%2B00+01+57.9%2C+-15+27+50%2C+1%29+%26++otype%3DStar+%0Avotable+close
	----------------------------------------- [astroquery.query]
/Users/bsipocz/munka/devel/astroquery/astroquery/simbad/core.py:135: UserWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'region(circle, ICRS, +00 01 57.9, -15 27 50, 1) &  otype=Star': java.text.ParseException: 
  warnings.warn("Warning: The script line number %i raised "
```

**Comment by bsipocz** [comment]
Having access to the query payload would help in fixing e.g. #2099, too.

**Comment by nkphysics** [comment]
I came across this again when doing some debugging, and decided to do a quick audit to see what has/doesn't have `get_query_payload` kwargs for anyone else looking at this.

Here's the list:

- [ ] ~~alfalfa~~ (Doesn't seem necessary, refer to #1285 for more info)
- [x] alma
- [ ] astrometry_net (#3555)
- [x] atomic
- [x] besancon
- [x] cadc
- [x] casda
- [ ] cosmosim
- [ ] ~~esa.euclid~~
- [ ] ~~esa.hsa~~
- [ ] ~~esa.hubble~~
- [ ] ~~esa.integral~~
- [ ] ~~esa.iso~~
- [ ] ~~esa.jwst~~
- [ ] ~~esa.xmm_newton~~
- [x] esasky
- [x] eso
- [ ] ~~exoplanet_orbit_database~~ (Seems unnecessary, will be/is deprecated, see #2792 for more info)
- [x] fermi
- [x] gaia (#3539)
- [x] gama
- [ ] gemini (#3568)
- [x] heasarc
- [x] hips2fits
- [x] hitran
- [x] imcce
- [ ] ipac.irsa.ibe
- [x] ipac.irsa.irsa_dust
- [x] ipac.ned
- [x] ipac.nexsci.nasa_exoplanet_archive
- [x] jplhorizons
- [x] jplsbdb
- [ ] lamda
- [x] linelists.cdms
- [x] linelists.cdms.jplspec
- [x] magpis
- [ ] ~~mast~~
- [x] mocserver
- [x] mpc
- [x] nasa-ads
- [x] nist
- [ ] ~~noirlab~~
- [x] nvas
- [x] oac
- [x] ogle (#3533) 
- [x] sdss
- [x] simbad
- [x] skyview
- [x] splatalogue
- [ ] ukidss
- [ ] ~~vamdc~~ (Deprecated, see #2070 for more info)
- [x] vizier
- [x] vo_conesearch
- [ ] vsa
- [x] wfau
- [x] xmatch

**Comment by bsipocz** [comment]
Thanks for triaging this.

I would say the kwarg make less sense for the VO-backed modules (all of ESA in your list, along with noirlab), and probably makes little sense for MAST, too. So overall we're quite close to be able to close the issue.
