### ISSUE TITLE
Fix or catch all warnings raised by the tests

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2057]
This is an umbrella issue for the warning cleanup, basically the exception list in `setup.cfg` has to be minimized to the bare minimum by removin the following (after they are either fixed in the codebase or properly catched). Some specific warnings have their own issue to provide smaller starter PR options for new contributors. I would suggest to address this issue gradually during a course of multiple, quicker, smaller PRs rather than one big one that is being around for a longer time:

- [x]     ignore::pytest.PytestUnraisableExceptionWarning (issue #2053) (PR #2520)
- [x]     ignore::numpy.VisibleDeprecationWarning (PR #2518)
- [x]     ignore: unclosed file:ResourceWarning (PR #2522)
- [x]     ignore::UserWarning (issue #2055) (PR #2520)
- [x]     ignore::astroquery.exceptions.InputWarning (PR #2520)
- [x]     ignore::astropy.utils.exceptions.AstropyDeprecationWarning (PR #2520)
- [x]     ignore::astropy.io.votable.exceptions.W50 (PR #2520)
- [x]     ignore::astropy.io.votable.exceptions.W06 (PR #2520)
- [x]     ignore::astropy.io.votable.exceptions.W03 (PR #2520)
- [ ]     ignore::astropy.io.votable.exceptions.W21
- [ ]     ignore::astropy.io.votable.exceptions.W42

**Comment by pllim** [comment]
As discussed in #2054, it is okay to blanket ignore all warnings from `vo_conesearch`.

**Comment by bsipocz** [comment]
Some of the vo warnings above are indeed coming from `vo_conesearch`, but roughly half of them originate in other modules while using `astropy.io.votable`. As opposed to `vo_conesearch` (which has its days numbered), those should ideally be fixed or properly caught.

**Comment by bsipocz** [comment]
I think #2520 does a big enough dent in this, as well as adds a detailed description to setup.cfg that I'll go ahead and close this issue.
